version: "3"
networks:
  postgresnet:

services:
  postgresql:
      image: postgres:latest
      hostname: cakes_postgresql
      container_name: cakes_postgresql
      restart: unless-stopped
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=AssortmentService
      ports:
        - 5432:5432
      networks:
        - postgresnet